# Generated by Django 4.0 on 2022-06-22 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATS_APP', '0004_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default='True'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default='False'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default='False'),
        ),
    ]
