# Generated by Django 4.0.5 on 2022-06-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATS_APP', '0008_user_is_staff_user_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant_document',
            name='document',
            field=models.FileField(upload_to='%Y/%m/%d'),
        ),
    ]
