# Generated by Django 4.0.5 on 2022-06-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATS_APP', '0009_alter_applicant_document_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant_document',
            name='document',
            field=models.FileField(upload_to=''),
        ),
    ]
