# Generated by Django 4.0.5 on 2022-06-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATS_APP', '0010_alter_applicant_document_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant_document',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, max_length=30),
        ),
    ]
