# Generated by Django 4.0 on 2022-06-27 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ATS_APP', '0011_alter_applicant_document_last_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill_set',
            name='skill_level',
        ),
    ]
