# Generated by Django 4.0.4 on 2022-06-27 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ATS_APP', '0011_alter_applicant_document_last_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill_set',
            name='skill_level',
        ),
        migrations.AlterField(
            model_name='skill_set',
            name='applicant_cv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
